name: $(BuildID)_$(Horton.Language)_$(Horton.Commit)_$(BuildDefinitionName)
variables:
- group: edge-e2e-node
  Horton.FrameworkRoot: $(Build.SourcesDirectory)
jobs:
- template: templates/jobs-gate-node.yaml
